package org.iiitb.se.links.utils;

public enum FragmentTypes {
  BOOKMARK_FRAGMENT,
  BOOKMARK_SEARCH_FRAGMENT,
  MY_GROUP_FRAGMENT,
  MY_GROUP_SEARCH_FRAGMENT,
  GROUP_REQUEST_FRAGMENT,
  ADD_BOOKMARK_FRAGMENT,
  GROUP_ADD_BOOKMARK_FRAGMENT,
  EDIT_BOOKMARK_FRAGMENT,
  GROUP_BOOKMARKS_FRAGMENT,
  GROUP_BOOKMARKS_SEARCH_FRAGMENT,
  SAVE_URL_FRAGMENT;    
}
